name: Workflow testing the server on multiple os

on:
  push:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

defaults:
  run:
    working-directory: mudfs

jobs:
  build-multiplat:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3.5.3
    - name: Use Node.js 18.17 on ${{ matrix.os }}
      uses: actions/setup-node@v3.7.0
      with:
        node-version: 18.17
    - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
